"""empty message

Revision ID: 26da593deab4
Revises: 3a3c97bebd6f
Create Date: 2021-02-23 14:16:51.859504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26da593deab4'
down_revision = '3a3c97bebd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'image_link')
    # ### end Alembic commands ###
