"""empty message

Revision ID: 3a3c97bebd6f
Revises: c81ac69555f2
Create Date: 2021-02-22 18:15:28.057234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3c97bebd6f'
down_revision = 'c81ac69555f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('schedule', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'schedule')
    # ### end Alembic commands ###
