"""empty message

Revision ID: 4b25efff0b23
Revises: 0def9a30e88e
Create Date: 2021-02-22 02:36:16.961169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b25efff0b23'
down_revision = '0def9a30e88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('schedule', sa.Date(), nullable=True))
    op.drop_column('shows', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('datetime', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'schedule')
    # ### end Alembic commands ###
