"""empty message

Revision ID: 7727dd64ee8a
Revises: 4b25efff0b23
Create Date: 2021-02-22 18:00:55.911536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7727dd64ee8a'
down_revision = '4b25efff0b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('schedule', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
