"""empty message

Revision ID: 7c9066833854
Revises: 7727dd64ee8a
Create Date: 2021-02-22 18:01:31.911210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9066833854'
down_revision = '7727dd64ee8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('schedule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'schedule')
    # ### end Alembic commands ###
