"""empty message

Revision ID: c81ac69555f2
Revises: 7c9066833854
Create Date: 2021-02-22 18:15:13.008559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81ac69555f2'
down_revision = '7c9066833854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('schedule', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
